apiVersion: v1
kind: Service
metadata:
  name: solidb
  namespace: solidb
  labels:
    app.kubernetes.io/name: solidb
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6745
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: solidb
    app.kubernetes.io/component: cluster
